package com.tonigames.fastreaction.findpair.ui.findpairfragment

import com.tonigames.fastreaction.R
import java.util.*

interface FindPairInteractionListener {
    fun onCorrectPairSelected()

    // wrong answer or time's up
    fun onFailedToSolve(msg: String = "")
}

interface IFindPairFragment {

    /** Returns a random element    */
    fun <E> List<E>.random(): E? = if (size > 0) get(Random().nextInt(size)) else null

    fun reduceDuration(duration: Long, roundCnt: Int?): Long {
        var newDuration = duration
        roundCnt?.let {
            newDuration = when {
                it > 20 -> (duration * 0.9).toLong()
                it > 40 -> (duration * 0.85).toLong()
                else -> duration
            }
        }

        return newDuration
    }

    companion object {
        val allDrawables: List<Int> = listOf(
            R.drawable.aircraft,
            R.drawable.amazon,
            R.drawable.american_football,
            R.drawable.android,
            R.drawable.ant,
            R.drawable.apple,
            R.drawable.audi,
            R.drawable.badminton,
            R.drawable.bakery,
            R.drawable.banana_juice,
            R.drawable.basketball,
            R.drawable.battle,
            R.drawable.beach,
            R.drawable.bear,
            R.drawable.bee,
            R.drawable.beer,
            R.drawable.bike,
            R.drawable.bikini,
            R.drawable.biscuit,
            R.drawable.bmw,
            R.drawable.boat,
            R.drawable.bomb,
            R.drawable.book,
            R.drawable.bowling,
            R.drawable.bug,
            R.drawable.burger,
            R.drawable.butterfly,
            R.drawable.cake,
            R.drawable.call,
            R.drawable.candy,
            R.drawable.carnival,
            R.drawable.cat,
            R.drawable.chicken,
            R.drawable.china_fan,
            R.drawable.china_flag,
            R.drawable.china_temple,
            R.drawable.chinese,
            R.drawable.christmas,
            R.drawable.church,
            R.drawable.clothes,
            R.drawable.cock,
            R.drawable.coffee_cup,
            R.drawable.company,
            R.drawable.construction_worker,
            R.drawable.crab,
            R.drawable.crane_truck,
            R.drawable.crown,
            R.drawable.deer,
            R.drawable.dinosaur,
            R.drawable.dinosaur_egg,
            R.drawable.doctor,
            R.drawable.dog,
            R.drawable.dog_food,
            R.drawable.donut,
            R.drawable.dragon,
            R.drawable.dumbbell,
            R.drawable.elephant,
            R.drawable.eagle,
            R.drawable.einstein,
            R.drawable.electric_car,
            R.drawable.facebook,
            R.drawable.fashion,
            R.drawable.fire,
            R.drawable.fire_truck,
            R.drawable.fish,
            R.drawable.flower,
            R.drawable.football,
            R.drawable.forest,
            R.drawable.france,
            R.drawable.furniture_household,
            R.drawable.gas,
            R.drawable.geisha,
            R.drawable.germany_flag,
            R.drawable.gift,
            R.drawable.goal,
            R.drawable.gold,
            R.drawable.grape,
            R.drawable.guitar,
            R.drawable.gym,
            R.drawable.hammer,
            R.drawable.heavy_equipment,
            R.drawable.hedgehog,
            R.drawable.hermit_crab,
            R.drawable.hippo,
            R.drawable.horsebak_riding,
            R.drawable.hotel,
            R.drawable.hot_air_balloon,
            R.drawable.huawei,
            R.drawable.jacket,
            R.drawable.jean,
            R.drawable.kitty,
            R.drawable.korea,
            R.drawable.law,
            R.drawable.lifestyle_girl,
            R.drawable.lifestyle_gitar,
            R.drawable.lighter,
            R.drawable.linkedin,
            R.drawable.lion,
            R.drawable.lollipop,
            R.drawable.macaron,
            R.drawable.macbook,
            R.drawable.magician,
            R.drawable.magic_wand,
            R.drawable.mail,
            R.drawable.mercedes,
            R.drawable.monkey,
            R.drawable.mouse_robot,
            R.drawable.ninja,
            R.drawable.octopus,
            R.drawable.owl,
            R.drawable.palm_tree,
            R.drawable.paper,
            R.drawable.paris,
            R.drawable.party,
            R.drawable.penguin,
            R.drawable.photography,
            R.drawable.piano,
            R.drawable.pig_red,
            R.drawable.professor,
            R.drawable.pumpkin,
            R.drawable.rabbit,
            R.drawable.racket,
            R.drawable.radio,
            R.drawable.ramen,
            R.drawable.rank,
            R.drawable.raphael,
            R.drawable.reading_glasses,
            R.drawable.real_estate,
            R.drawable.ring,
            R.drawable.rocket,
            R.drawable.rodent,
            R.drawable.running_shoes,
            R.drawable.samurai,
            R.drawable.santa_claus,
            R.drawable.sashimi,
            R.drawable.satellite,
            R.drawable.shark,
            R.drawable.sheep,
            R.drawable.shell,
            R.drawable.shipped,
            R.drawable.smoke,
            R.drawable.snake,
            R.drawable.snow,
            R.drawable.snowboard,
            R.drawable.snowman,
            R.drawable.socks,
            R.drawable.speaker,
            R.drawable.squirrel,
            R.drawable.statue_liberty,
            R.drawable.submarine,
            R.drawable.summer,
            R.drawable.summer_ice,
            R.drawable.sunflower,
            R.drawable.supermarket,
            R.drawable.surfing,
            R.drawable.sushi,
            R.drawable.swans,
            R.drawable.swiss_knife,
            R.drawable.tank,
            R.drawable.telephone,
            R.drawable.tiger,
            R.drawable.toilet,
            R.drawable.town,
            R.drawable.tractor,
            R.drawable.train,
            R.drawable.trampoline,
            R.drawable.travel,
            R.drawable.truck,
            R.drawable.truck_construction,
            R.drawable.tv,
            R.drawable.uk,
            R.drawable.under_construction,
            R.drawable.unicorn,
            R.drawable.vegetable,
            R.drawable.video_cameras,
            R.drawable.violin,
            R.drawable.volkswagen,
            R.drawable.volvo,
            R.drawable.war_canon,
            R.drawable.watermelon,
            R.drawable.whale,
            R.drawable.wine,
            R.drawable.xiaomi
        )
    }
}
